export const UPDATE_MENU = 'UPDATE_MENU';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
